
MAIN_MENU = (
    '\n Действия:'
    '\n1 - Погода в моем городе '
    '\n2 - Погода в конкретном городе'
    '\n3 - История запросов '
    '\n4 - Удаление истории запросов'
    '\n5 - Выход'
)
OPTIONS = '\nВыберите действие: '
ENTER_CITY = '\nВведите название города: '
NUMBER_OF_REQUEST = '\nВведите количество желаемых запросов: '
EXIT = '\nВыход '
ALL_REMOVED = '\nВсе запросы удалены '
PRINTED_ALL_REQUESTS = '\nВыведены все записи: '


SEPARATION_LINE = '\n------------------------------------------- '
CURRENT_TIME = '\nТекущее время: '
CITY_NAME = '\nНазвание города: '
WEATHER_CONDITIONS = '\nПогодные условия: '
TEMPERATURE = '\nТекущая температура: '
TEMPERATURE_FEELS_LIKE = '\nОщущается как: '
WIND_SPEED = '\nСкорость ветра: '
CELSIUS = ' градусов по  цельсию'
MS = ' м/с'

INCORRECT_MAIN_MENU_ENTRY = '\n<<< Некорректный ввод, введите еще раз >>> '
NEGATIVE_NUMBER_ENTRY = '\n<<< Введите положительное число >>> '
ValueError_TEXT = '\n<<< Введите целое число >>> '
SaveStorageError_TEXT = '\n<<< Сохранение не было совершено >>> '
OpenStorageError_TEXT = '\n<<< Не удалось открыть историю запросов>>> '
GeocoderError_TEXT = '\n<<< Не удалось распознать ваше местоположение >>> '
MissCityError_TEXT = '\n<<< Город не найден >>> '
ApiRequestError_TEXT = '\n<<< Не удалось получить ответ от сервера >>> '
TypeError_TEXT = '\n<<< Неверный тип данных>>> '
TypeMenuError_TEXT = '\n<<< Некорректный ввод, введите еще раз >>> '
LostConnectionError_TEXT = '\n<<< Не удалось установить соединение >>> '
ExceptionError_TEXT = '\n<<< Неизвестная ошибка >>> '
TimeOutError_TEXT = '\n<<< Время ожидания слишком велико >>> '
